final List<String> termsOfService = [
  introduction,
  string1,
  privacy,
  software,
  accountsAndSecurity,
  termsOfUse,
  violationOfTermsOfService,
  feedback,
  generalRules,
  accpet
];
final String introduction =
    "1.         GIỚI THIỆU\n1.1       Chào mừng bạn đến với sàn giao dịch thương mại điện tử BookStore qua giao diện website hoặc ứng dụng di động (“Trang BookStore”). Trước khi sử dụng Trang BookStore hoặc tạo tài khoản BookStore (“Tài Khoản”), vui lòng đọc kỹ các Điều Khoản Dịch Vụ dưới đây và Quy Chế Hoạt Động Sàn Giao Dịch Thương Mại Điện Tử BookStore để hiểu rõ quyền lợi và nghĩa vụ hợp pháp của mình đối với Công ty TNHH BookStore và các công ty liên kết và công ty con của BookStore (sau đây được gọi riêng là “BookStore”, gọi chung là “chúng tôi”, “của chúng tôi”). “Dịch Vụ” chúng tôi cung cấp hoặc sẵn có bao gồm (a) Trang BookStore, (b) các dịch vụ được cung cấp bởi Trang BookStore và bởi phần mềm dành cho khách hàng của BookStore có sẵn trên Trang BookStore, và (c) tất cả các thông tin, đường dẫn, tính năng, dữ liệu, văn bản, hình ảnh, biểu đồ, âm nhạc, âm thanh, video (bao gồm cả các đoạn video được đăng tải trực tiếp theo thời gian thực (livestream)), tin nhắn, tags, nội dung, chương trình, phần mềm, ứng dụng dịch vụ (bao gồm bất kỳ ứng dụng dịch vụ di động nào) hoặc các tài liệu khác có sẵn trên Trang BookStore hoặc các dịch vụ liên quan đến Trang BookStore (“Nội Dung”). Bất kỳ tính năng mới nào được bổ sung hoặc mở rộng đối với Dịch Vụ đều thuộc phạm vi điều chỉnh của Điều Khoản Dịch Vụ này. Điều Khoản Dịch Vụ này điều chỉnh việc  bạn sử dụng Dịch Dụ cung cấp bởi BookStore.\n"
    "1.2       Dịch Vụ bao gồm dịch vụ sàn giao dịch trực tuyến kết nối người tiêu dùng với nhau nhằm mang đến cơ hội kinh doanh giữa người mua (“Người Mua”) và người bán (“Người Bán”) (gọi chung là “bạn”, “Người Sử Dụng” hoặc “Các Bên”). Hợp đồng mua bán thật sự là trực tiếp giữa Người Mua và Người Bán. Các Bên liên quan đến giao dịch đó sẽ chịu trách nhiệm đối với hợp đồng mua bán giữa họ, việc đăng bán hàng hóa, bảo hành sản phẩm và tương tự. BookStore không can thiệp vào giao dịch giữa các Người Sử Dụng. BookStore có thể hoặc không sàng lọc trước Người Sử Dụng hoặc Nội Dung hoặc thông tin cung cấp bởi Người Sử Dụng. BookStore bảo lưu quyền loại bỏ bất cứ Nội Dung hoặc thông tin nào trên Trang BookStore theo Mục 6.4 bên dưới. BookStore không bảo đảm cho việc các Người Sử Dụng sẽ thực tế hoàn thành giao dịch. Lưu ý, BookStore sẽ là bên trung gian quản lý tình trạng hàng hóa và mua bán giữa Người Mua và Người Bán và quản lý vấn đề chuyển phát, trừ khi Người Mua và Người Bán thể hiện mong muốn tự giao dịch với nhau một cách rõ ràng.\n"
    "1.3       Trước khi trở thành Người Sử Dụng của Trang BookStore, bạn cần đọc và chấp nhận mọi điều khoản và điều kiện được quy định trong, và dẫn chiếu đến, Điều Khoản Dịch Vụ này và Chính Sách Bảo Mật được dẫn chiếu theo đây.\n"
    "1.4       BookStore bảo lưu quyền thay đổi, chỉnh sửa, tạm ngưng hoặc chấm dứt tất cả hoặc bất kỳ phần nào của Trang BookStore hoặc Dịch Vụ vào bất cứ thời điểm nào theo qui định pháp luật. Phiên Bản thử nghiệm của Dịch Vụ hoặc tính năng của Dịch Vụ có thể không hoàn toàn giống với phiên bản cuối cùng.\n"
    "1.5       BookStore bảo lưu quyền từ chối yêu cầu mở Tài Khoản hoặc các truy cập của bạn tới Trang BookStore hoặc Dịch Vụ theo quy định pháp luật và Điều khoản dịch vụ.\n";
final String string1 =
    " BẰNG VIỆC SỬ DỤNG DỊCH VỤ HAY TẠO TÀI KHOẢN TẠI BookStore, BẠN ĐÃ CHẤP NHẬN VÀ ĐỒNG Ý VỚI NHỮNG ĐIỀU KHOẢN DỊCH VỤ NÀY VÀ CHÍNH SÁCH BỔ SUNG ĐƯỢC DẪN CHIẾU THEO ĐÂY.\n"
    "NẾU BẠN KHÔNG ĐỒNG Ý VỚI NHỮNG ĐIỀU KHOẢN DỊCH VỤ NÀY, VUI LÒNG KHÔNG SỬ DỤNG DỊCH VỤ HOẶC TRUY CẬP VÀO TRANG BookStore. NẾU BẠN LÀ NGƯỜI CHƯA THÀNH NIÊN HOẶC BỊ GIỚI HẠN VỀ NĂNG LỰC HÀNH VI DÂN SỰ THEO QUY ĐỊNH PHÁP LUẬT TẠI QUỐC GIA BẠN SINH SỐNG, BẠN CẦN NHẬN ĐƯỢC SỰ HỖ TRỢ HOẶC CHẤP THUẬN TỪ CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP, TÙY TỪNG TRƯỜNG HỢP ÁP DỤNG, ĐỂ MỞ TÀI KHOẢN HOẶC SỬ DỤNG DỊCH VỤ. TRONG TRƯỜNG HỢP ĐÓ, CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP, TÙY TỪNG TRƯỜNG HỢP ÁP DỤNG, CẦN HỖ TRỢ ĐỂ BẠN HIỂU RÕ HOẶC THAY MẶT BẠN CHẤP NHẬN NHỮNG ĐIỀU KHOẢN TRONG THỎA THUẬN DỊCH VỤ NÀY. NẾU BẠN CHƯA CHẮC CHẮN VỀ ĐỘ TUỔI CŨNG NHƯ NĂNG LỰC HÀNH VI DÂN SỰ CỦA MÌNH, HOẶC CHƯA HIỂU RÕ CÁC ĐIỀU KHOẢN NÀY CŨNG NHƯ QUY ĐỊNH PHÁP LUẬT CÓ LIÊN QUAN ÁP DỤNG CHO ĐỘ TUỔI HOẶC NĂNG LỰC HÀNH VI DÂN SỰ CỦA MÌNH, VUI LÒNG KHÔNG TẠO TÀI KHOẢN HOẶC SỬ DỤNG DỊCH VỤ CHO ĐẾN KHI NHẬN ĐƯỢC SỰ GIÚP ĐỠ TỪ CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP. NẾU BẠN LÀ CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP CỦA NGƯỜI CHƯA THÀNH NIÊN HOẶC BỊ GIỚI HẠN VỀ NĂNG LỰC HÀNH VI DÂN SỰ, TÙY TỪNG TRƯỜNG HỢP THEO QUY ĐỊNH PHÁP LUẬT, BẠN CẦN HỖ TRỢ ĐỂ NGƯỜI ĐƯỢC GIÁM HỘ HIỂU RÕ HOẶC ĐẠI DIỆN NGƯỜI ĐƯỢC GIÁM HỘ CHẤP NHẬN CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY VÀ CHỊU TRÁCH NHIỆM ĐỐI VỚI TOÀN BỘ QUÁ TRÌNH SỬ DỤNG TÀI KHOẢN HOẶC CÁC DỊCH VỤ CỦA BookStore  MÀ KHÔNG PHÂN BIỆT TÀI KHOẢN ĐÃ  HOẶC SẼ ĐƯỢC TẠO LẬP.\n";

final String privacy = " 2.         QUYỀN RIÊNG TƯ\n"
    "2.1       BookStore coi trọng việc bảo mật thông tin của bạn. Để bảo vệ quyền lợi người dùng, BookStore cung cấp Chính Sách Bảo Mật tại BookStore để giải thích chi tiết các hoạt động bảo mật của BookStore. Vui lòng tham khảo Chính Sách Bảo Mật để biết cách thức BookStore thu thập và sử dụng thông tin liên quan đến Tài Khoản và/hoặc việc sử dụng Dịch Vụ của Người Sử Dụng (“Thông Tin Người Sử Dụng”). Điều Khoản Dịch Vụ này có liên quan mật thiết với Chính Sách Bảo Mật. Bằng cách sử dụng Dịch Vụ hoặc cung cấp thông tin trên Trang BookStore, Người Sử Dụng:\n"
    "a.         cho phép BookStore thu thập, sử dụng, công bố và/hoặc xử lý các Nội Dung, dữ liệu cá nhân của bạn và Thông Tin Người Sử Dụng như được quy định trong Chính Sách Bảo Mật;\n"
    "b.         đồng ý và công nhận rằng các thông tin được cung cấp trên Trang BookStore sẽ thuộc sở hữu chung của bạn và BookStore;\n"
    "c.         sẽ không, dù là trực tiếp hay gián tiếp, tiết lộ các Thông Tin Người Sử Dụng cho bất kỳ bên thứ ba nào, hoặc bằng bất kỳ phương thức nào cho phép bất kỳ bên thứ ba nào được truy cập hoặc sử dụng Thông Tin Người Dùng của bạn.\n"
    "2.2       Trường hợp Người Sử Dụng sở hữu dữ liệu cá nhân của Người Sử Dụng khác thông qua việc sử dụng Dịch Vụ (“Bên Nhận Thông Tin”) theo đây đồng ý rằng, mình sẽ (i) tuân thủ mọi qui định pháp luật về bảo vệ an toàn thông tin cá nhân liên quan đến những thông tin đó; (ii) cho phép Người Sử Dụng là chủ sở hữu của các thông thông tin cá nhân mà Bên Nhận Thông Tin thu thập được (“Bên Tiết Lộ Thông Tin”) được phép xóa bỏ thông tin của mình được thu thập từ cơ sở dữ liệu của Bên Nhận Thông Tin; và (iii) cho phép Bên Tiết Lộ Thông Tin rà soát những thông tin đã được thu thập về họ bởi Bên Nhận Thông Tin, phù hợp với hoặc theo yêu cầu của các qui định pháp luật hiện hành.\n";
final String software = "3.         PHẦN MỀM\n"
    "Bất kỳ phần mềm nào được cung cấp bởi BookStore tới Người Sử Dụng đều thuộc phạm vi điều chỉnh của các Điều Khoản Dịch Vụ này. BookStore bảo lưu tất cả các quyền liên quan đến phần mềm không được cấp một các rõ ràng bởi BookStore theo đây. Bất kỳ tập lệnh hoặc mã code, liên kết đến hoặc dẫn chiếu từ Dịch Vụ, đều được cấp phép cho bạn bởi các bên thứ ba là chủ sở hữu của tập lệnh hoặc mã code đó chứ không phải bởi BookStore.\n";
final String accountsAndSecurity = " 4.         TÀI KHOẢN VÀ BẢO MẬT\n"
    "4.1       Một vài tính năng của Dịch Vụ chúng tôi yêu cầu phải đăng ký một Tài Khoản bằng cách lựa chọn một tên người sử dụng không trùng lặp (“Tên Đăng Nhập”) và mật khẩu đồng thời cung cấp một số thông tin cá nhân nhất định. Bạn có thể sử dụng Tài Khoản của mình để truy cập vào các sản phẩm, website hoặc dịch vụ khác mà BookStore cho phép, có mối liên hệ hoặc đang hợp tác. BookStore không kiểm tra và không chịu trách nhiệm đối với bất kỳ nội dung, tính năng năng, bảo mật, dịch vụ, chính sách riêng tư, hoặc cách thực hiện khác của các sản phẩm, website hay dịch vụ đó.. Trường hợp bạn sử dụng Tài Khoản của mình để truy cập vào các sản phẩm, website hoặc dịch vụ khác mà BookStore cho phép, có mối liên hệ hoặc đang hợp tác, các điều khoản dịch vụ của những sản phẩm, website hoặc dịch vụ đó, bao gồm các chính sách bảo mật tương ứng vẫn được áp dụng khi bạn sử dụng các sản phẩm, website hoặc dịch vụ đó ngay cả khi những điều khoản dịch vụ này khác với Điều Khoản Dịch Vụ và/hoặc Chính Sách Bảo Mật của BookStore.\n"
    "4.2       Bạn đồng ý (a) giữ bí mật mật khẩu và chỉ sử dụng Tên Đăng Nhập và mật khẩu khi đăng nhập, (b) đảm bảo bạn sẽ đăng xuất khỏi tài khoản của mình sau mỗi phiên đăng nhập trên Trang BookStore, và (c) thông báo ngay lập tức với BookStore nếu phát hiện bất kỳ việc sử dụng trái phép nào đối với Tài Khoản, Tên Đăng Nhập và/hoặc mật khẩu của bạn. Bạn phải chịu trách nhiệm với hoạt động dưới Tên Đăng Nhập và Tài Khoản của mình, bao gồm tổn thất hoặc thiệt hại phát sinh từ việc sử dụng trái phép liên quan đến mật khẩu hoặc từ việc không tuân thủ Điều Khoản này của Người Sử Dụng.\n"
    "4.3       Bạn đồng ý rằng BookStore có toàn quyền xóa Tài Khoản và Tên Đăng Nhập của Người Sử Dụng ngay lập tức, gỡ bỏ hoặc hủy từ Trang BookStore bất kỳ Nội Dung nào liên quan đến Tài Khoản và Tên Đăng Nhập của Người Sử Dụng với bất kỳ lý do nào mà có hoặc không cần thông báo hay chịu trách nhiệm với Người Sử Dụng hay bên thứ ba nào khác. Căn cứ để thực hiện các hành động này có thể bao gồm (a) Tài Khoản và Tên Đăng Nhập không hoạt động trong thời gian dài, (b) vi phạm điều khoản hoặc tinh thần của các Điều Khoản Dịch Vụ này, (c) có hành vi bất hợp pháp, lừa đảo, quấy rối, xâm phạm, đe dọa hoặc lạm dụng, (d) có nhiều tài khoản người dùng khác nhau, (e) mua sản phẩm trên Trang BookStore với mục đích kinh doanh, (f) mua hàng số lượng lớn từ một Người Bán hoặc một nhóm Người Bán có liên quan, (g) lạm dụng mã giảm giá hoặc tài trợ hoặc quyền lợi khuyến mại (bao gồm việc bán mã giảm giá cho các bên thứ ba cũng như lạm dụng mã giảm giá ở Trang BookStore), (h) có hành vi gây hại tới những Người Sử Dụng khác, các bên thứ ba hoặc các lợi ích kinh tế của BookStore. Việc sử dụng Tài Khoản cho các mục đích bất hợp pháp, lừa đảo, quấy rối, xâm phạm, đe dọa hoặc lạm dụng có thể được gửi cho cơ quan nhà nước có thẩm quyền theo quy định pháp luật.\n"
    "4.4       Người Sử Dụng có thể yêu cầu xóa tài khoản bằng cách thông báo bằng văn bản đến BookStore (tại đây). Tuy nhiên, Người Sử Dụng vẫn phải chịu trách nhiệm và nghĩa vụ đối với bất kỳ giao dịch nào chưa hoàn thành (phát sinh trước hoặc sau khi tài khoản bị xóa) hay việc vận chuyển hàng hóa liên quan đến tài khoản bị yêu cầu xóa. Khi đó, theo Điều Khoản Dịch Vụ, Người Sử Dụng phải liên hệ với BookStore sau khi đã nhanh chóng và hoàn tất việc thực hiện và hoàn thành các giao dịch chưa hoàn tất. Người Sử Dụng chịu trách nhiệm đối với yêu cầu xóa tài khoản của mình.\n"
    "4.5       Bạn chỉ có thể sử dụng Dịch Vụ và/hoặc mở Tài Khoản tại BookStore nếu bạn đáp ứng đủ các điều kiện để chấp nhận Điều Khoản Dịch Vụ này.\n";
final String termsOfUse = "5.         ĐIỀU KHOẢN SỬ DỤNG\n"
    "5.1       Quyền được phép sử dụng Trang BookStore và Dịch Vụ có hiệu lực cho đến khi bị chấm dứt. Quyền được phép sử dụng sẽ bị chấm dứt theo Điều Khoản Dịch Vụ này hoặc trường hợp Người Sử Dụng vi phạm bất cứ điều khoản hoặc điều kiện nào được quy định tại Điều Khoản Dịch Vụ này. Trong trường hợp đó, BookStore có thể chấm dứt việc sử dụng của Người Sử Dụng bằng hoặc không cần thông báo.\n"
    "5.2       Người Sử Dụng không được phép:\n"
    "(a)        tải lên, đăng, truyền tải hoặc bằng cách khác công khai bất cứ Nội Dung nào trái pháp luật, có hại, đe dọa, lạm dụng, quấy rối, gây hoang mang, lo lắng, xuyên tạc, phỉ báng, xúc phạm, khiêu dâm, bôi nhọ, xâm phạm quyền riêng tư của người khác, gây căm phẫn, hoặc phân biệt chủng tộc, dân tộc hoặc bất kỳ nội dung không đúng đắn nào khác;\n"
    "(b)        vi phạm pháp luật, quyền lợi của bên thứ ba hoặc Chính Sách Cấm/Hạn Chế Sản Phẩm của BookStore;\n"
    "(c)        đăng tải, truyền tin, hoặc bằng bất kỳ hình thức nào khác hiển thị bất kỳ Nội dung nào có sự xuất hiện của người chưa thành niên hoặc sử dụng Dịch vụ gây tổn hại cho người chưa thành niên dưới bất kỳ hình thức nào;\n"
    "(d)        sử dụng Dịch Vụ hoặc đăng tải Nội Dung để mạo danh bất kỳ cá nhân hoặc tổ chức nào, hoặc bằng cách nào khác xuyên tạc cá nhân hoặc tổ chức;\n"
    "(e)        giả mạo các tiêu đề hoặc bằng cách khác ngụy tạo các định dạng nhằm che giấu nguồn gốc của bất kỳ Nội Dung nào được tryền tải thông qua Dịch Vụ;\n"
    "(f)        gỡ bỏ bất kỳ thông báo độc quyền nào từ Trang BookStore;\n"
    "(g)        gây ra, chấp nhận hoặc ủy quyền cho việc sửa đổi, cấu thành các sản phẩm phái sinh, hoặc chuyển thể của Dich Vụ mà không được sự cho phép rõ ràng của BookStore;\n"
    "(h)        sử dụng Dịch Vụ phục vụ lợi ích của bất kỳ bên thứ ba nào hoặc bất kỳ hành vi nào không được chấp nhận theo Điều Khoản Dịch Vụ này;\n"
    "(i)         sử dụng Dịch Vụ hoặc đăng tải Nội Dung cho mục đích gian lận, không hợp lý, sai trái, gây hiểu nhầm hoặc gây nhầm lẫn;\n"
    "(j)         mở và vận hành nhiều tài khoản người dùng khác nhau liên quan đến bất kỳ hành vi nào vi phạm điều khoản hoặc tinh thần của Điều Khoản Dịch Vụ này;\n"
    "(k)        truy cập sàn giao dịch thương mại điện tử BookStore, mở tài khoản hoặc bằng cách khác truy cập tài khoản người dùng của mình thông qua bất kỳ phần mềm hoặc phần cứng không được chấp thuận hoặc cung cấp bởi BookStore, bao gồm phần mềm giả lập, thiết bị giả lập, phần mềm tự động hoặc bất kỳ phần mềm, thiết bị hoặc phần cứng nào có chức năng tương tự.\n"
    "(l)         chỉnh sửa giá của bất kỳ sản phẩm nào hoặc can thiệp vào danh mục hàng hóa của Người Sử Dụng khác.\n"
    "(m)       thực hiện bất kỳ hành động nào làm sai lệch hệ thống đánh giá hoặc tiếp nhận phản hồi của BookStore;\n"
    "(n)        cố gắng chuyển đổi mã chương trình, đảo ngược kỹ thuật, tháo gỡ hoặc xâm nhập (hack) Dịch Vụ (hoặc bất cứ hợp phần nào theo đó); hoặc phá bỏ hoặc vượt qua bất kỳ công nghệ mã hóa hoặc biện pháp bảo mật nào được BookStore áp dụng đối với các Dịch Vụ và/hoặc các dữ liệu được truyền tải, xử lý hoặc lưu trữ bởi BookStore;\n"
    "(o)        khai thác hoặc thu thập bất kỳ thông tin nào liên quan đến Tài Khoản của Người  Sử Dụng khác, bao gồm bất kỳ thông tin hoặc dữ liệu cá nhân nào;\n"
    "(p)        tải lên, gửi thư điện tử, đăng, chuyển tải hoặc bằng cách khác công khai bất kỳ Nội Dung nào mà bạn không được cho phép theo bất kỳ luật hoặc quan hệ hợp đồng hoặc tín thác nào (chẳng hạn thông tin nội bộ, thông tin độc quyền và thông tin mật được biết hoặc tiết lộ như một phần của quan hệ lao động hoặc theo các thỏa thuận bảo mật);\n"
    "(q)        tải lên, gửi thư điện tử, đăng, chuyển tải hoặc bằng cách khác công khai bất kỳ Nội Dung nào dẫn đến trường hợp vi phạm các quyền về sáng chế, thương hiệu, bí quyết kinh doanh, bản quyền hoặc bất cứ đặc quyền nào của bất cứ bên nào;\n"
    "(r)        tải lên, gửi thư điện tử, đăng, chuyển tải hoặc bằng cách khác công khai bất kỳ quảng cáo, các tài liệu khuyến mại, “thư quấy rối”, “thư rác”, “chuỗi ký tự” không được phép hoặc không hợp pháp, hoặc bất kỳ hình thức lôi kéo không được phép nào khác;\n"
    "(s)        tải lên, gửi thư điện tử, đăng, chuyển tải hoặc bằng cách khác công khai bất cứ tài liệu chứa các loại vi-rút, worm, trojan hoặc bất kỳ các mã, tập tin hoặc chương trình máy tính được thiết kế để trực tiếp hoặc gián tiếp gây cản trở, điều khiển, gián đoạn, phá hỏng hoặc hạn chế các chức năng hoặc tổng thể của bất kỳ phần mềm hoặc phần cứng hoặc dữ liệu hoặc thiết bị viễn thông của máy tính;\n"
    "(t)         làm gián đoạn các dòng tương tác thông thường, đẩy nhanh tốc độ “lướt (scroll)” màn hình hơn những Người Sử Dụng khác có thể đối với Dịch Vụ, hoặc bằng cách khác thực hiện thao tác gây ảnh hưởng tiêu cực đến khả năng tham gia giao dịch thực của những Người Sử Dụng khác,\n"
    "(u)        can thiệp, điều khiển hoặc làm gián đoạn Dịch Vụ hoặc máy chủ hoặc hệ thống được liên kết với Dịch Vụ hoặc tới việc sử dụng và trải nghiệm Dịch Vụ của Người Sử Dụng khác, hoặc không tuân thủ bất kỳ các yêu cầu, quy trình, chính sách và luật lệ đối với các hệ thống được liên kết với Trang BookStore;\n"
    "(v)        thực hiện bất kỳ hành động hoặc hành vi nào có thể trực tiếp hoặc gián tiếp phá hủy, vô hiệu hóa, làm quá tải, hoặc làm suy yếu Dịch Vụ hoặc máy chủ hoặc hệ thống liên kết với Dịch Vụ;\n"
    "(w)       sử dụng Dịch Vụ để vi phạm pháp luật, quy chế, quy tắc, chỉ thị, hướng dẫn, chính sách áp dụng của địa phương, liên bang, quốc gia hoặc quốc tế (có hoặc chưa có hiệu lực) một cách có chủ ý hoặc vô ý liên quan đến phòng chống rửa tiền hoặc phòng chống khủng bố;\n"
    "(x)        sử dụng Dịch Vụ để vi phạm hoặc phá vỡ bất kỳ hình phạt hay lệnh cấm vận nào  được quản lý hay thực thi bởi các cơ quan có liên quan.\n"
    "(y)        sử dụng Dịch Vụ để xâm hại tới quyền riêng tư của người khác hoặc để “lén theo dõi” hoặc bằng cách khác quấy rối người khác;\n"
    "(z)        xâm phạm các quyền của BookStore, bao gồm bất kỳ quyền sở hữu trí tuệ và gây nhầm lẫn cho các quyền đó;\n"
    "(aa)      sử dụng Dịch vụ để thu thập hoặc lưu trữ dữ liệu cá nhân của Người Sử Dụng khác liên quan đến các hành vi và hoạt động bị cấm như đề cập ở trên; và/hoặc\n"
    "(ab)      liệt kê các hàng hóa xâm phạm quyền tác giả, nhãn hiệu hoặc các quyền sở hữu trí tuệ khác của các bên thứ ba hoặc sử dụng Dịch Vụ theo các cách thức có thể xâm phạm đến quyền sở hữu trí tuệ của các bên khác.\n"
    "5.3       Người Sử Dụng hiểu rằng các Nội Dung, dù được đăng công khai hoặc truyền tải riêng tư, là hoàn toàn thuộc trách nhiệm của người đã tạo ra Nội Dung đó.  Điều đó nghĩa là bạn, không phải BookStore, phải hoàn toàn chịu trách nhiệm đối với những Nội Dung mà bạn tải lên, đăng, gửi thư điện tử, chuyển tải hoặc bằng cách nào khác công khai trên Trang BookStore. Người Sử Dụng hiểu rằng bằng cách sử dụng Trang BookStore, bạn có thể gặp phải Nội Dung mà bạn cho là phản cảm, không đúng đắn hoặc chưa phù hợp. BookStore sẽ không chịu trách nhiệm đối với Nội Dung, bao gồm lỗi hoặc thiếu sót liên quan đến Nội Dung, hoặc tổn thất hoặc thiệt hại xuất phát từ việc sử dụng, hoặc dựa trên, Nội Dung được đăng tải, gửi thư, chuyển tải hoặc bằng cách khác công bố trên Trang BookStore.\n"
    "5.4       Người Sử Dụng thừa nhận rằng BookStore và các bên được chỉ định của mình có toàn quyền (nhưng không có nghĩa vụ) sàng lọc, từ chối, xóa, dừng, tạm dừng, gỡ bỏ hoặc dời bất kỳ Nội Dung có sẵn trên Trang BookStore, bao gồm bất kỳ Nội Dung hoặc thông tin nào bạn đã đăng.  BookStore có quyền gỡ bỏ Nội Dung (i) xâm phạm đến Điều Khoản Dịch Vụ; (ii) trong trường hợp BookStore nhận được khiếu nại hơp lệ theo quy định pháp luật từ Người Sử Dụng khác; (iii) trong trường hợp BookStore nhận được thông báo hợp lệ về vi phạm quyền sở hữu trí tuệ hoặc yêu cầu pháp lý cho việc gỡ bỏ; hoặc (iv) những nguyên nhân khác theo quy định pháp luật. BookStore có quyền chặn các liên lạc (bao gồm việc cập nhật trạng thái, đăng tin, truyền tin và/hoặc tán gẫu) về hoặc liên quan đến Dịch Vụ như nỗ lực của chúng tôi nhằm bảo vệ Dịch Vụ hoặc Người Sử Dụng của BookStore, hoặc bằng cách khác thi hành các điều khoản trong Điều Khoản Dịch Vụ này. Người Sử Dụng đồng ý rằng mình phải đánh giá, và chịu mọi rủi ro liên quan đến, việc sử dụng bất kỳ Nội Dung nào, bao gồm bất kỳ việc dựa vào tính chính xác, đầy đủ, hoặc độ hữu dụng của Nội Dung đó. Liên quan đến vấn đề này, Người Sử Dụng thừa nhận rằng mình không phải và, trong giới hạn tối đa pháp luật cho phép, không cần dựa bào bất kỳ Nội Dung nào được tạo bởi BookStore hoặc gửi cho BookStore, bao gồm các thông tin trên các Diễn Đàn BookStore hoặc trên các phần khác của Trang BookStore.\n"
    "5.5       Người Sử Dụng chấp thuận và đồng ý rằng BookStore có thể truy cập, duy trì và tiết lộ thông tin Tài Khoản của Người Sử Dụng trong trường hợp pháp luật có yêu cầu hoặc theo lệnh của tòa án hoặc cơ quan chính phủ hoặc cơ quan nhà nước có thẩm quyền yêu cầu BookStore hoặc những nguyên nhân khác theo quy định pháp luật: (a) tuân thủ các thủ tục pháp luật; (b) thực thi Điều Khoản Dịch Vụ; (c) phản hồi các khiếu nại về việc Nội Dung xâm phạm đến quyền lợi của bên thứ ba; (d) phản hồi các yêu cầu của Người Sử Dụng liên quan đến chăm sóc khách hàng; hoặc (e) bảo vệ các quyền, tài sản hoặc an toàn của BookStore, Người Sử Dụng và/hoặc cộng đồng.\n";
final String violationOfTermsOfService =
    "6.         VI PHẠM ĐIỀU KHOẢN DỊCH VỤ\n"
    "6.1       Việc vi phạm chính sách này có thể dẫn tới một số hành động, bao gồm bất kỳ hoặc tất cả các hành động sau:\n"
    "-           Xóa danh mục sản phẩm;\n"
    "-           Giới hạn quyền sử dụng Tài Khoản;\n"
    "-           Đình chỉ và chấm dứt Tài Khoản;\n"
    "-           Thu hồi tiền/tài sản có được do hành vi gian lận, và các chi phí có liên quan như chi phí vận chuyển của đơn hàng, phí thanh toán…;\n"
    "-           Cáo buộc hình sự;\n"
    "-           Áp dụng biện pháp dân sự, bao gồm khiếu nại bồi thường thiệt hại và/hoặc áp dụng biện pháp khẩn cấp tạm thời;\n"
    "-           Các hành động hoặc biện pháp chế tài khác theo Tiêu Chuẩn Cộng Đồng, Quy Chế Hoạt Động, hoặc các Chính Sách BookStore.\n"
    "6.2       Nếu bạn phát hiện Người Sử Dụng trên Trang BookStore của chúng tôi có hành vi vi phạm Điều Khoản Dịch Vụ, vui lòng liên hệ BookStore\n";

final String feedback = "7.       PHẢN HỒI\n"
    "7.1     BookStore luôn đón nhận những thông tin và phản hồi từ phía Người Sử Dụng nhằm giúp BookStore cải thiện chất lượng Dịch Vụ.  Vui lòng xem thêm quy trình phản hồi của BookStore dưới đây:\n"
    "(ii)        Phản hồi cần được thực hiện bằng văn bản qua email hoặc sử dụng mẫu phản hồi có sẵn trên ứng dụng.\n"
    "(iii)       Tất cả các phản hồi ẩn danh đều không được chấp nhận.\n"
    "(iv)       Người Sử Dụng liên quan đến phản hồi sẽ được thông báo đầy đủ và được tạo cơ hội cải thiện tình hình.\n"
    "(v)        Những phản hồi không rõ ràng và mang tính phỉ báng sẽ không được chấp nhận\n";
final String generalRules = "8.       QUY ĐỊNH CHUNG\n"
    "8.1     BookStore bảo lưu tất cả các quyền lợi không được trao theo đây.\n"
    "8.2     BookStore có quyền chỉnh sửa các Điều Khoản Dịch Vụ này vào bất cứ thời điểm nào thông qua việc đăng tải các Điều Khoản Dịch Vụ được chỉnh sửa lên Trang BookStore.  Việc Người Dùng tiếp tục sử dụng Trang BookStore sau khi việc thay đổi được đăng tải sẽ cấu thành việc Người Sử Dụng chấp nhận các Điều Khoản Dịch Vụ được chỉnh sửa.\n"
    "8.3     Người Sử Dụng không được phép chuyển giao, cấp lại quyền hoặc chuyển nhượng bất kỳ các quyền hoặc nghĩa vụ được cấp cho Người Sử Dụng theo đây.\n"
    "8.4     Không một quy định nào trong các Điều Khoản Dịch Vụ này sẽ cấu thành quan hệ đối tác, liên doanh hoặc quan hệ đại lý – chủ sở hữu giữa bạn và BookStore.\n"
    "8.5     Tại bất kỳ hoặc các thời điểm nào, nếu BookStore không thể thực hiện được bất kỳ điều khoản nào theo đây sẽ không ảnh hưởng, dưới bất kỳ hình thức nào, đến các quyền của BookStore vào thời điểm sau đó để thực thi các quyền này trừ khi việc thư thi các quyền này được miễn trừ bằng văn bản.\n"
    "8.6     Các Điều Khoản Dịch Vụ này hoàn toàn phục vụ cho lợi ích của BookStore và Người Sử Dụng mà vì lợi ích của bất kỳ cá nhân hay tổ chức nào khác, trừ các công ty liên kết và các công ty con của BookStore (và cho từng bên kế thừa hay bên nhận chuyển giao của BookStore hoặc của các công ty liên kết và công ty con của BookStore).\n"
    "8.7     Các điều khoản được quy định trong Điều Khoản Dịch Vụ này và bất kỳ các thỏa thuận và chính sách được bao gồm hoặc được dẫn chiếu trong các Điều Khoản Dịch Vụ này cấu thành nên sự thỏa thuận và cách hiểu tổng thể của các bên đối với Dịch Vụ và Trang BookStore và thay thế bất kỳ thỏa thuận hoặc cách hiểu trước đây giữa các bên liên quan đến vấn đề đó.   Với việc các bên giao kết thỏa thuận được tạo thành theo các Điều Khoản Dịch Vụ này, các bên không dựa vào bất kỳ tuyên bố, khẳng định, đảm bảo, cách hiểu, cam kết, lời hứa hoặc cam đoan nào của bất kỳ người nào trừ những điều được nêu rõ trong các Điều Khoản Dịch Vụ này.  Các Điều Khoản Dịch Vụ này có thể sẽ không mâu thuẫn, giải thích hoặc bổ sung như là bằng chứng của các thỏa thuận trước, bất kỳ thỏa thuận miệng hiện tại nào hoặc bất kỳ các điều khoản bổ sung nhất quán nào.\n"
    "8.8     Bạn đồng ý tuân thủ mọi quy định pháp luật hiện hành liên quan đến chống tham nhũng và chống hối lộ.\n"
    "8.9     Nếu bạn có bất kỳ câu hỏi hay thắc mắc nào liên quan đến Điều Khoản Dịch Vụ hoặc các vấn đề phát sinh liên quan đến Điều Khoản Dịch Vụ trên Trang BookStore, vui lòng liên hệ BookStore\n";

final String accpet =
    "TÔI ĐÃ ĐỌC CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY VÀ ĐỒNG Ý VỚI TẤT CẢ CÁC ĐIỀU KHOẢN NHƯ TRÊN CŨNG NHƯ BẤT KỲ ĐIỀU KHOẢN NÀO ĐƯỢC CHỈNH SỬA SAU NÀY.  BẰNG CÁCH BẤM NÚT “ĐĂNG KÝ” HOẶC “ĐĂNG KÝ QUA FACEBOOK” KHI ĐĂNG KÝ SỬ DỤNG TRANG BookStore, TÔI HIỂU RẰNG TÔI ĐANG TẠO CHỮ KÝ ĐIỆN TỬ MÀ TÔI HIỂU RẰNG NÓ CÓ GIÁ TRỊ VÀ HIỆU LỰC TƯƠNG TỰ NHƯ CHỮ KÝ TÔI KÝ BẰNG TAY.\n";
